// GENERATED by tool/protocol/generate.dart from tool/protocol/spec.dart. Do not edit.
//
// cef_host wire opcodes (windows).
#ifndef FLUTTER_CEF_WINDOWS_CEF_HOST_OPCODES_H_
#define FLUTTER_CEF_WINDOWS_CEF_HOST_OPCODES_H_

#include <cstdint>

namespace flutter_cef {

constexpr uint8_t kCefHostProtocolVersion = 4;

// ---- cef_host -> plugin ----
// {u64 bridgeHandle}{u32 srcW}{u32 srcH}: bridgeHandle is the DXGI legacy
// shared handle of the host-minted bridge texture.
constexpr uint8_t kOpPresent = 0x01;
// {u8 readyFlags}{u8 protocolVersion} on browserId 0, before any browser
// exists. readyFlags bit0 = ad-hoc (mock keychain) build; Windows sends 0.
constexpr uint8_t kOpReady = 0x02;
// {u32 cef_cursor_type_t}
constexpr uint8_t kOpCursor = 0x03;
// {utf8 message}; browserId 0 = process-level
constexpr uint8_t kOpLog = 0x04;
// {u8 loading}{u8 canGoBack}{u8 canGoForward}
constexpr uint8_t kOpLoadState = 0x05;
// {utf8 title}
constexpr uint8_t kOpTitle = 0x06;
// {utf8 main-frame url}
constexpr uint8_t kOpUrl = 0x07;
// {u32 code}{utf8 "url\ntext"}
constexpr uint8_t kOpLoadErr = 0x08;
// {u32 level}{utf8 "source:line\tmsg"}
constexpr uint8_t kOpConsole = 0x09;
// {utf8 url} main-frame load started
constexpr uint8_t kOpPageStart = 0x0a;
// {utf8 url} main-frame load finished
constexpr uint8_t kOpPageFinish = 0x0b;
// {u32 percent 0-100}
constexpr uint8_t kOpProgress = 0x0c;
// {utf8 url} popup / target=_blank
constexpr uint8_t kOpNewWindow = 0x0d;
// {u32 count}{u32 activeOrdinal}{u8 final}
constexpr uint8_t kOpFindResult = 0x0e;
// {u32 id}{u32 type}{u32 msgLen}{utf8 msg}{utf8 defaultText}
constexpr uint8_t kOpJsDialog = 0x0f;
// {utf8 "id:json"} reply to kOpEvalReturning
constexpr uint8_t kOpEvalResult = 0x16;
// {utf8 "name:message"} JS channel -> plugin
constexpr uint8_t kOpChannelMsg = 0x17;
// {utf8 suggestedName} a download started
constexpr uint8_t kOpDownload = 0x18;
// {u32 x}{u32 y}{u32 w}{u32 h} caret rect (DIP)
constexpr uint8_t kOpImeBounds = 0x19;
// {u32 id}{utf8 json-array} reply to kOpVisitCookies
constexpr uint8_t kOpCookies = 0x1a;
// {utf8 targetId} this browser's CDP targetId, reply to kOpResolveTargetId
constexpr uint8_t kOpTargetId = 0x1b;
// {} OnAfterCreated: the browser is up; the plugin paces the next create on it
constexpr uint8_t kOpCreated = 0x1c;
// {} the async CreateBrowser dispatch failed; the plugin drops the session
constexpr uint8_t kOpCreateFailed = 0x1d;

// ---- plugin -> cef_host ----
// {u8 type}{u8 button}{u8 clickCount}{u8 pad}{u32 modifiers}{f64 x}{f64 y}{f64
// dx}{f64 dy}; type 0=move 1=down 2=up 3=wheel 4=leave, button 0=left 1=middle
// 2=right, x/y in DIP
constexpr uint8_t kOpPointer = 0x10;
// {u32 w}{u32 h}[{f64 dpr}]: dpr absent or 0 = unchanged, must be in (0, 8]
constexpr uint8_t kOpResize = 0x11;
// {u8 type}{u8 pad x3}{u32 modifiers}{u32 windowsKeyCode}{u32
// nativeKeyCode}{u32 character}; type 0=rawkeydown 2=keyup 3=char
constexpr uint8_t kOpKey = 0x12;
// {u32 w}{u32 h}{f64 dpr}{utf8 url}; the frame's browserId is the NEW id; empty
// url = about:blank
constexpr uint8_t kOpCreateBrowser = 0x13;
// {} on browserId 0: end the whole process
constexpr uint8_t kOpShutdown = 0x14;
// {} close one browser; the process survives
constexpr uint8_t kOpDisposeBrowser = 0x15;
// {utf8 url}
constexpr uint8_t kOpNavigate = 0x20;
// {}
constexpr uint8_t kOpReload = 0x21;
// {}
constexpr uint8_t kOpStop = 0x22;
// {}
constexpr uint8_t kOpBack = 0x23;
// {}
constexpr uint8_t kOpForward = 0x24;
// {utf8 code}
constexpr uint8_t kOpExecuteJs = 0x25;
// {f64 level}; factor = 1.2^level
constexpr uint8_t kOpSetZoom = 0x26;
// {u8 forward}{u8 matchCase}{u8 findNext}{utf8 text}
constexpr uint8_t kOpFind = 0x27;
// {u8 clearSelection}; absent = 1
constexpr uint8_t kOpStopFind = 0x28;
// {u32 id}{u8 ok}{utf8 text}
constexpr uint8_t kOpJsDialogResp = 0x29;
// {u32 id}{utf8 expression}; replies kOpEvalResult
constexpr uint8_t kOpEvalReturning = 0x2a;
// {utf8 name} register a JS channel
constexpr uint8_t kOpAddChannel = 0x2b;
// {utf8
// url\0name\0value\0domain\0path[\0secure(0|1)\0httpOnly(0|1)\0sameSite(unspecified|none|lax|strict)]}
constexpr uint8_t kOpSetCookie = 0x2c;
// {} delete all cookies
constexpr uint8_t kOpClearCookies = 0x2d;
// {u32 id}{utf8 url}; empty url = all; replies kOpCookies
constexpr uint8_t kOpVisitCookies = 0x2e;
// {utf8 url\0name}
constexpr uint8_t kOpDeleteCookie = 0x2f;
// {utf8 text} IME composition update
constexpr uint8_t kOpImeSetComp = 0x30;
// {utf8 text} commit composed text
constexpr uint8_t kOpImeCommit = 0x31;
// {} cancel composition
constexpr uint8_t kOpImeCancel = 0x32;
// {} open DevTools in a window
constexpr uint8_t kOpShowDevTools = 0x33;
// {utf8 url} a load by the embedder, exempt from the scheme allowlist
constexpr uint8_t kOpLoadTrusted = 0x34;
// {u8 visible}; absent = 1
constexpr uint8_t kOpSetVisible = 0x35;
// {} replies kOpTargetId
constexpr uint8_t kOpResolveTargetId = 0x36;
// {} force a repaint, to re-kick a stalled first frame
constexpr uint8_t kOpInvalidate = 0x37;
// {u8 cmd} in the focused frame: 0=copy 1=cut 2=paste 3=selectAll 4=undo 5=redo
constexpr uint8_t kOpEditCommand = 0x38;
// {utf8 baseUrl}\0{utf8 html}: store-only; serve html as the main-frame
// response for exactly baseUrl (empty html clears it). The load is a following
// kOpCreateBrowser or kOpLoadTrusted for that URL
constexpr uint8_t kOpSetAuthoredHtml = 0x3f;
// ({u8 kind}{u32 len}{utf8})*, kind 0 = JS channel name, 1 = script
// (document_start.h): store-only, for the browser created right behind it
constexpr uint8_t kOpSetDocumentStart = 0x41;

}  // namespace flutter_cef

#endif  // FLUTTER_CEF_WINDOWS_CEF_HOST_OPCODES_H_
