// Writes the per-package copies of the cef_host wire protocol from spec.dart.
//
//   dart run tool/protocol/generate.dart           # rewrite the copies
//   dart run tool/protocol/generate.dart --check   # exit 1 if any is stale
//
// Run from the repository root.
import 'dart:io';

import 'spec.dart';

const _banner = 'GENERATED by tool/protocol/generate.dart from '
    'tool/protocol/spec.dart. Do not edit.';

const macosHeaderPath =
    'packages/flutter_cef_macos/native/cef_host/cef_host_opcodes.h';
const macosSwiftPath =
    'packages/flutter_cef_macos/macos/Classes/CefHostOpcodes.swift';
const windowsHeaderPath =
    'packages/flutter_cef_windows/native/cef_host/cef_host_opcodes.h';
const windowsDocPath =
    'packages/flutter_cef_windows/native/cef_host/PROTOCOL.md';

const docBegin =
    '<!-- BEGIN GENERATED OPCODES (tool/protocol/generate.dart) -->';
const docEnd = '<!-- END GENERATED OPCODES -->';

String hex(int code) => '0x${code.toRadixString(16).padLeft(2, '0')}';

String lowerCamel(String s) => s[0].toLowerCase() + s.substring(1);

List<Op> opsOn(Platform p) {
  final list = ops.where((o) => o.platforms.contains(p)).toList()
    ..sort((a, b) => a.code.compareTo(b.code));
  return list;
}

/// [text] as comment lines of at most [width] columns, each starting [prefix].
List<String> comment(String text, String prefix, {int width = 80}) {
  final lines = <String>[];
  var line = prefix;
  for (final word in text.split(' ')) {
    if (line.length > prefix.length && line.length + 1 + word.length > width) {
      lines.add(line);
      line = prefix;
    }
    line = line.length > prefix.length ? '$line $word' : '$line$word';
  }
  lines.add(line);
  return lines;
}

String _direction(Direction d) =>
    d == Direction.toPlugin ? 'cef_host -> plugin' : 'plugin -> cef_host';

String cppHeader(Platform p) {
  final guard = p == Platform.macos
      ? 'FLUTTER_CEF_MACOS_CEF_HOST_OPCODES_H_'
      : 'FLUTTER_CEF_WINDOWS_CEF_HOST_OPCODES_H_';
  final b = StringBuffer()
    ..writeln('// $_banner')
    ..writeln('//')
    ..writeln('// cef_host wire opcodes (${p.name}).')
    ..writeln('#ifndef $guard')
    ..writeln('#define $guard')
    ..writeln()
    ..writeln('#include <cstdint>')
    ..writeln();
  if (p == Platform.windows) {
    b
      ..writeln('namespace flutter_cef {')
      ..writeln();
  }
  b.writeln('constexpr uint8_t kCefHostProtocolVersion = '
      '${protocolVersions[p]};');
  for (final d in Direction.values) {
    b
      ..writeln()
      ..writeln('// ---- ${_direction(d)} ----');
    for (final o in opsOn(p).where((o) => o.direction == d)) {
      comment(o.payloadOn(p), '// ').forEach(b.writeln);
      b.writeln('constexpr uint8_t kOp${o.name} = ${hex(o.code)};');
    }
  }
  if (p == Platform.windows) {
    b
      ..writeln()
      ..writeln('}  // namespace flutter_cef');
  }
  b
    ..writeln()
    ..writeln('#endif  // $guard');
  return b.toString();
}

String swiftFile() {
  final b = StringBuffer()
    ..writeln('// $_banner')
    ..writeln()
    ..writeln(
        '/// The cef_host wire protocol version this plugin speaks; a host '
        'announcing')
    ..writeln('/// another is refused.')
    ..writeln('enum CefHostProtocol {')
    ..writeln(
        '  static let version: UInt8 = ${protocolVersions[Platform.macos]}')
    ..writeln('}')
    ..writeln()
    ..writeln('/// cef_host wire opcodes.')
    ..writeln('enum CefOp {');
  var first = true;
  for (final d in Direction.values) {
    if (!first) b.writeln();
    first = false;
    b.writeln('  // ---- ${_direction(d)} ----');
    for (final o in opsOn(Platform.macos).where((o) => o.direction == d)) {
      comment(o.payloadOn(Platform.macos), '  /// ').forEach(b.writeln);
      b.writeln('  static let ${lowerCamel(o.name)}: UInt8 = ${hex(o.code)}');
    }
  }
  b.writeln('}');
  return b.toString();
}

String docTable() {
  final b = StringBuffer()
    ..writeln(docBegin)
    ..writeln()
    ..writeln('Protocol version ${protocolVersions[Platform.windows]}. '
        'Payload integers are big-endian.');
  for (final d in Direction.values) {
    b
      ..writeln()
      ..writeln('### ${_direction(d)}')
      ..writeln()
      ..writeln('| Op | Name | Payload |')
      ..writeln('|---|---|---|');
    for (final o in opsOn(Platform.windows).where((o) => o.direction == d)) {
      final payload = o.payloadOn(Platform.windows).replaceAll('|', r'\|');
      b.writeln('| ${hex(o.code)} | kOp${o.name} | $payload |');
    }
  }
  final macOnly = ops
      .where((o) => !o.platforms.contains(Platform.windows))
      .map((o) => '${hex(o.code)} kOp${o.name}')
      .join(', ');
  b
    ..writeln()
    ..writeln('macOS only, never reuse on Windows: $macOnly.')
    ..writeln()
    ..write(docEnd);
  return b.toString();
}

/// [current] with the generated opcode table swapped in.
String withDocTable(String current) {
  final start = current.indexOf(docBegin);
  final end = current.indexOf(docEnd);
  if (start < 0 || end < start) {
    throw StateError('$windowsDocPath has no generated-opcodes markers');
  }
  return current.replaceRange(start, end + docEnd.length, docTable());
}

/// Every generated file, by path from the repository root, as it should read.
Map<String, String> generatedFiles(String root) => {
      macosHeaderPath: cppHeader(Platform.macos),
      macosSwiftPath: swiftFile(),
      windowsHeaderPath: cppHeader(Platform.windows),
      windowsDocPath: withDocTable(File('$root/$windowsDocPath')
          .readAsStringSync()
          .replaceAll('\r\n', '\n')),
    };

void main(List<String> args) {
  final check = args.contains('--check');
  var stale = false;
  generatedFiles('.').forEach((path, content) {
    final file = File(path);
    if (file.existsSync() &&
        file.readAsStringSync().replaceAll('\r\n', '\n') == content) {
      return;
    }
    if (check) {
      stderr.writeln('stale: $path');
      stale = true;
    } else {
      file.writeAsStringSync(content);
      stdout.writeln('wrote $path');
    }
  });
  if (stale) {
    stderr.writeln('Run: dart run tool/protocol/generate.dart');
    exit(1);
  }
}
