// GENERATED by tool/protocol/generate.dart from tool/protocol/spec.dart. Do not edit.

/// The cef_host wire protocol version this plugin speaks; a host announcing
/// another is refused.
enum CefHostProtocol {
  static let version: UInt8 = 9
}

/// cef_host wire opcodes.
enum CefOp {
  // ---- cef_host -> plugin ----
  /// {u32 iosurfaceId}{u32 srcW}{u32 srcH}: a frame was presented. srcW/srcH
  /// are the physical pixel size of the composited frame.
  static let present: UInt8 = 0x01
  /// {u8 readyFlags}{u8 protocolVersion} on browserId 0, before any browser
  /// exists. readyFlags bit0 = ad-hoc (mock keychain) build; Windows sends 0.
  static let ready: UInt8 = 0x02
  /// {u32 cef_cursor_type_t}
  static let cursor: UInt8 = 0x03
  /// {utf8 message}; browserId 0 = process-level
  static let log: UInt8 = 0x04
  /// {u8 loading}{u8 canGoBack}{u8 canGoForward}
  static let loadState: UInt8 = 0x05
  /// {utf8 title}
  static let title: UInt8 = 0x06
  /// {utf8 main-frame url}
  static let url: UInt8 = 0x07
  /// {u32 code}{utf8 "url\ntext"}
  static let loadErr: UInt8 = 0x08
  /// {u32 level}{utf8 "source:line\tmsg"}
  static let console: UInt8 = 0x09
  /// {utf8 url} main-frame load started
  static let pageStart: UInt8 = 0x0a
  /// {utf8 url} main-frame load finished
  static let pageFinish: UInt8 = 0x0b
  /// {u32 percent 0-100}
  static let progress: UInt8 = 0x0c
  /// {utf8 url} popup / target=_blank
  static let newWindow: UInt8 = 0x0d
  /// {u32 count}{u32 activeOrdinal}{u8 final}
  static let findResult: UInt8 = 0x0e
  /// {u32 id}{u32 type}{u32 msgLen}{utf8 msg}{utf8 defaultText}
  static let jsDialog: UInt8 = 0x0f
  /// {utf8 "id:json"} reply to kOpEvalReturning
  static let evalResult: UInt8 = 0x16
  /// {utf8 "name:message"} JS channel -> plugin
  static let channelMsg: UInt8 = 0x17
  /// {utf8 suggestedName} a download started
  static let download: UInt8 = 0x18
  /// {u32 x}{u32 y}{u32 w}{u32 h} caret rect (DIP)
  static let imeBounds: UInt8 = 0x19
  /// {u32 id}{utf8 json-array} reply to kOpVisitCookies
  static let cookies: UInt8 = 0x1a
  /// {utf8 targetId} this browser's CDP targetId, reply to kOpResolveTargetId
  static let targetId: UInt8 = 0x1b
  /// {} OnAfterCreated: the browser is up; the plugin paces the next create on
  /// it
  static let created: UInt8 = 0x1c
  /// {} the async CreateBrowser dispatch failed; the plugin drops the session
  static let createFailed: UInt8 = 0x1d
  /// {u32 id}{u32 requested}{utf8 origin} getUserMedia with no remembered
  /// decision; answer with kOpMediaResponse
  static let mediaRequest: UInt8 = 0x1e
  /// {u8 videoActive}{u8 audioActive}{u8 setting 0=ask 1=allow} the page's
  /// camera/mic status
  static let mediaState: UInt8 = 0x1f
  /// {u32 id}{utf8 json} right-click: Chromium's menu model and params, for the
  /// plugin's consumer to draw; answer with kOpContextMenuCommand
  static let contextMenu: UInt8 = 0x40

  // ---- plugin -> cef_host ----
  /// {u8 type}{u8 button}{u8 clickCount}{u8 pad}{u32 modifiers}{f64 x}{f64
  /// y}{f64 dx}{f64 dy}; type 0=move 1=down 2=up 3=wheel 4=leave, button 0=left
  /// 1=middle 2=right, x/y in DIP
  static let pointer: UInt8 = 0x10
  /// {u32 w}{u32 h}[{f64 dpr}]: dpr absent or 0 = unchanged, must be in (0, 8]
  static let resize: UInt8 = 0x11
  /// {u8 type}{u8 pad x3}{u32 modifiers}{u32 windowsKeyCode}{u32
  /// nativeKeyCode}{u32 character}; type 0=rawkeydown 2=keyup 3=char
  static let key: UInt8 = 0x12
  /// {u32 w}{u32 h}{f64 dpr}{utf8 url}; the frame's browserId is the NEW id;
  /// empty url = about:blank
  static let createBrowser: UInt8 = 0x13
  /// {} on browserId 0: end the whole process
  static let shutdown: UInt8 = 0x14
  /// {} close one browser; the process survives
  static let disposeBrowser: UInt8 = 0x15
  /// {utf8 url}
  static let navigate: UInt8 = 0x20
  /// {}
  static let reload: UInt8 = 0x21
  /// {}
  static let stop: UInt8 = 0x22
  /// {}
  static let back: UInt8 = 0x23
  /// {}
  static let forward: UInt8 = 0x24
  /// {utf8 code}
  static let executeJs: UInt8 = 0x25
  /// {f64 level}; factor = 1.2^level
  static let setZoom: UInt8 = 0x26
  /// {u8 forward}{u8 matchCase}{u8 findNext}{utf8 text}
  static let find: UInt8 = 0x27
  /// {u8 clearSelection}; absent = 1
  static let stopFind: UInt8 = 0x28
  /// {u32 id}{u8 ok}{utf8 text}
  static let jsDialogResp: UInt8 = 0x29
  /// {u32 id}{utf8 expression}; replies kOpEvalResult
  static let evalReturning: UInt8 = 0x2a
  /// {utf8 name} register a JS channel
  static let addChannel: UInt8 = 0x2b
  /// {utf8
  /// url\0name\0value\0domain\0path[\0secure(0|1)\0httpOnly(0|1)\0sameSite(unspecified|none|lax|strict)]}
  static let setCookie: UInt8 = 0x2c
  /// {} delete all cookies
  static let clearCookies: UInt8 = 0x2d
  /// {u32 id}{utf8 url}; empty url = all; replies kOpCookies
  static let visitCookies: UInt8 = 0x2e
  /// {utf8 url\0name}
  static let deleteCookie: UInt8 = 0x2f
  /// {utf8 text} IME composition update
  static let imeSetComp: UInt8 = 0x30
  /// {utf8 text} commit composed text
  static let imeCommit: UInt8 = 0x31
  /// {} cancel composition
  static let imeCancel: UInt8 = 0x32
  /// {} or {u32 x}{u32 y}: open DevTools in a window, inspecting the element at
  /// the point if given
  static let showDevTools: UInt8 = 0x33
  /// {utf8 url} a load by the embedder, exempt from the scheme allowlist
  static let loadTrusted: UInt8 = 0x34
  /// {u8 visible}; absent = 1
  static let setVisible: UInt8 = 0x35
  /// {} replies kOpTargetId
  static let resolveTargetId: UInt8 = 0x36
  /// {} force a repaint, to re-kick a stalled first frame
  static let invalidate: UInt8 = 0x37
  /// {u8 cmd} in the focused frame: 0=copy 1=cut 2=paste 3=selectAll 4=undo
  /// 5=redo
  static let editCommand: UInt8 = 0x38
  /// {utf8 url} open a windowed browser, sharing the tile's cookies, for a
  /// WebAuthn ceremony the tile can't host
  static let openAuthWindow: UInt8 = 0x39
  /// {u8 muted}
  static let setAudioMuted: UInt8 = 0x3a
  /// {u16 ms} visible begin-frame cadence, clamped to [8, 250]
  static let setPumpInterval: UInt8 = 0x3b
  /// {u32 id}{u8 allow}{u8 remember} answer a kOpMediaRequest; remembered per
  /// origin only when remember is set
  static let mediaResponse: UInt8 = 0x3c
  /// {u8 0=ask 1=allow 2=block} rewrite the current origin's camera+mic
  /// setting; applies the next time the page asks
  static let setMediaSetting: UInt8 = 0x3d
  /// {u32 id}{u32 commandId} run the chosen kOpContextMenu command; 0 =
  /// dismissed
  static let contextMenuCommand: UInt8 = 0x3e
  /// {utf8 baseUrl}\0{utf8 html}: store-only; serve html as the main-frame
  /// response for exactly baseUrl (empty html clears it). The load is a
  /// following kOpCreateBrowser or kOpLoadTrusted for that URL
  static let setAuthoredHtml: UInt8 = 0x3f
  /// ({u8 kind}{u32 len}{utf8})*, kind 0 = JS channel name, 1 = script
  /// (document_start.h): store-only, for the browser created right behind it
  static let setDocumentStart: UInt8 = 0x41
}
